### PR TITLE
Auto configurations conditional on web application

### LINKED ISSUE #405: Add @ConditionalOnWebApplication for those autoconfigurations depending on web
I use `problem-spring-web-starter:0.25.2` and want to run `@SpringBootTest` with `spring.main.web-application-type=none`.

The application context can't be initialized as the `SecurityProblemSupport` depends on some beans only created for web contexts. All configurations depending on those beans, should be guarded with `@ConditionalOnWebApplication` so that they won't be loaded.

Error Output:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in org.zalando.problem.spring.web.advice.security.SecurityProblemSupport required a bean of type 'org.springframework.web.servlet.HandlerExceptionResolver' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Qualifier(value="handlerExceptionResolver")

The following candidates were found but could not be injected:
	- Bean method 'errorAttributes' in 'ErrorMvcAutoConfiguration' not loaded because not a servlet web application


Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.web.servlet.HandlerExceptionResolver' in your configuration.
```

### PR DESCRIPTION
**Pull request by whiskeysierra**
## Motivation and Context

Fixes #405. Replaces #406.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: problem-spring-web-autoconfigure/src/test/java/org/zalando/problem/spring/web/autoconfigure/security/SecurityTest.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+import org.junit.jupiter.api.Test;
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
+import org.springframework.boot.test.context.SpringBootTest;
+import org.springframework.context.annotation.Configuration;
+import org.springframework.security.config.annotation.web.builders.HttpSecurity;
+import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
+import org.zalando.problem.spring.web.advice.AdviceTrait;
+import org.zalando.problem.spring.web.advice.security.SecurityAdviceTrait;
```
Comment (whiskeysierra) [inline problem-spring-web-autoconfigure/src/test/java/org/zalando/problem/spring/web/autoconfigure/security/SecurityTest.java]: Codacy Issue found: [Avoid unused imports such as 'org.zalando.problem.spring.web.advice.security.SecurityAdviceTrait'](https://app.codacy.com/app/whiskeysierra/problem-spring-web/pullRequest?prid=4612907)

File: problem-spring-web-autoconfigure/src/main/java/org/zalando/problem/spring/web/autoconfigure/security/ProblemSecurityAutoConfiguration.java [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+import org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration;
+import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
+import org.zalando.problem.spring.web.advice.AdviceTrait;
+import org.zalando.problem.spring.web.advice.security.SecurityProblemSupport;
+import org.zalando.problem.spring.web.autoconfigure.ProblemAutoConfiguration;
+
+import static org.apiguardian.api.API.Status.INTERNAL;
+
+@API(status = INTERNAL)
+@AllArgsConstructor(onConstructor = @__(@Autowired))
```
Comment (lukasniemeier-zalando) [inline problem-spring-web-autoconfigure/src/main/java/org/zalando/problem/spring/web/autoconfigure/security/ProblemSecurityAutoConfiguration.java]: opinion piece: a plain written ctx with the annotation would be more comprehensible in such a case :thermometer:

**Comment by lukasniemeier-zalando** [comment]
:+1:
