### PR TITLE
Fixed formatting of object names

### LINKED ISSUE #16: ObjectError's ObjectName is not formatted correctly
Fields are formatted using `formatFieldName`, but object names (for top-level validations) are not:

### PR DESCRIPTION
**Pull request by whiskeysierra**
This fixes #16

### CODE REVIEW

**Comment by lukasniemeier-zalando** [comment]
:+1:

File: src/test/java/org/zalando/problem/spring/web/advice/ExceptionHandling.java [hunk 1]
```diff
@@ -20,8 +20,15 @@
...
 
+import com.google.common.base.CaseFormat;
 import org.springframework.web.bind.annotation.ControllerAdvice;
 
 @ControllerAdvice
 public final class ExceptionHandling implements ProblemHandling {
+
+    @Override
+    public String formatFieldName(String fieldName) {
+        return CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, fieldName);
```
Comment (jhorstmann) [inline src/test/java/org/zalando/problem/spring/web/advice/ExceptionHandling.java]: Can we make this configurable or somehow access the naming conventions of the objectmapper used for deserializing the request?

Comment (whiskeysierra) [inline src/test/java/org/zalando/problem/spring/web/advice/ExceptionHandling.java]: > Can we make this configurable or somehow access the naming conventions of the objectmapper used for deserializing the request?

I don't think there is a way to access anything related to deserialization at this point. The second problem, even if we would be able to access the `PropertyNamingStrategy` - it only works on annotated elements or fields, nothing we can reliably reproduce at this point.
