### PR TITLE
Explicitely require handlerExceptionResolver

### LINKED ISSUE #72: ProblemAuthenticationEntryPoint in spring-boot app
Integrating the *ProblemAuthenticationEntryPoint* as described in the [README](https://github.com/zalando/problem-spring-web#security) leads to the following exception on starting a [*spring-boot* application](https://github.com/spring-guides/gs-securing-web/tree/master/complete):

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field resolver in org.zalando.problem.spring.web.advice.security.ProblemAuthenticationEntryPoint required a single bean, but 2 were found:
        - errorAttributes: defined by method 'errorAttributes' in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration.class]
        - handlerExceptionResolver: defined by method 'handlerExceptionResolver' in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

Which one to pick?

### PR DESCRIPTION
**Pull request by whiskeysierra**
Fixes #72

### CODE REVIEW

File: src/main/java/org/zalando/problem/spring/web/advice/security/ProblemAuthenticationEntryPoint.java [hunk 1]
```diff
@@ -14,8 +15,13 @@
 @Component
 public class ProblemAuthenticationEntryPoint implements AuthenticationEntryPoint {
 
+    private final HandlerExceptionResolver resolver;
+
     @Autowired
-    private HandlerExceptionResolver resolver;
+    public ProblemAuthenticationEntryPoint(
+            @Qualifier("handlerExceptionResolver") final HandlerExceptionResolver resolver) {
```
Comment (lukasniemeier-zalando) [inline src/main/java/org/zalando/problem/spring/web/advice/security/ProblemAuthenticationEntryPoint.java]: In this case a comment (e..g on the class) might be helpful for future generations.

> AuthenticationEntryPoint forwarding authentication exceptions to spring-webmvc's HandlerExceptionResolver as defined by WebMvcConfigurationSupport. Compatible with spring-webmvc 4.3.3.

This might help someone in case the Spring guys decide to rename the bean.
